name: PluginCMD
version: 1.1
main: lokiPM\PluginCMD\Main
api: 5.0.0
src-namespace-prefix: lokiPM\PluginCMD

commands:
  plenable:
    description: Enable a Plugin.
    permission: plugincmd.use
  pldisable:
    description: Disable a Plugin.
    permission: plugincmd.use

permissions:
  plugincmd.use:
    default: op
